export const styles = {
    app: {
        fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "Segoe UI", sans-serif',
        background: '#f5f5f7',
        minHeight: '100vh',
    },
    header: {
        background: 'rgba(255, 255, 255, 0.95)',
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid #e5e5e7',
        position: 'sticky',
        top: 0,
        zIndex: 1000,
    },
    headerContent: {
        maxWidth: '1400px',
        margin: '0 auto',
        padding: '16px 20px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        textDecoration: 'none',
        color: '#1d1d1f',
    },
    logoIcon: {
        fontSize: '28px',
    },
    logoText: {
        fontSize: '21px',
        fontWeight: 600,
        letterSpacing: '-0.02em',
    },
    userAvatar: {
        width: '32px',
        height: '32px',
        borderRadius: '50%',
        background: '#1d1d1f',
        color: '#fff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '14px',
        fontWeight: 600,
        cursor: 'pointer',
    },
    container: {
        maxWidth: '800px',
        margin: '0 auto',
        padding: '60px 20px',
    },
    formWrapper: {
        background: '#fff',
        borderRadius: '18px',
        padding: '48px',
        border: '1px solid #e5e5e7',
        minHeight: '600px',
        display: 'flex',
        flexDirection: 'column',
    },
    formHeader: {
        marginBottom: '40px',
        textAlign: 'center',
    },
    formTitle: {
        fontSize: '36px',
        fontWeight: 600,
        color: '#1d1d1f',
        marginBottom: '8px',
        letterSpacing: '-0.02em',
    },
    formSubtitle: {
        fontSize: '17px',
        color: '#6e6e73',
    },
    progressContainer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '48px',
        position: 'relative',
    },
    stepItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        position: 'relative',
        flex: 1,
    },
    stepCircle: {
        width: '48px',
        height: '48px',
        borderRadius: '50%',
        background: '#e5e5e7',
        color: '#6e6e73',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '18px',
        fontWeight: 600,
        marginBottom: '12px',
        transition: 'all 0.3s',
        zIndex: 1,
    },
    stepCircleActive: {
        background: '#1d1d1f',
        color: '#fff',
        transform: 'scale(1.1)',
    },
    stepCircleComplete: {
        background: '#1d1d1f',
        color: '#fff',
    },
    stepLabel: {
        fontSize: '14px',
        fontWeight: 500,
        color: '#6e6e73',
    },
    stepLine: {
        position: 'absolute',
        top: '24px',
        left: '50%',
        right: '-50%',
        height: '2px',
        background: '#e5e5e7',
        zIndex: 0,
    },
    stepLineComplete: {
        background: '#1d1d1f',
    },
    stepContent: {
        flex: 1,
        marginBottom: '32px',
    },
    fadeIn: {
        animation: 'fadeIn 0.3s ease-in',
    },
    stepTitle: {
        fontSize: '28px',
        fontWeight: 600,
        color: '#1d1d1f',
        marginBottom: '8px',
    },
    stepDescription: {
        fontSize: '15px',
        color: '#6e6e73',
        marginBottom: '32px',
    },
    formGroup: {
        marginBottom: '24px',
    },
    label: {
        display: 'block',
        fontSize: '15px',
        fontWeight: 500,
        color: '#1d1d1f',
        marginBottom: '8px',
    },
    required: {
        color: '#cc0000',
    },
    input: {
        width: '100%',
        padding: '14px 16px',
        fontSize: '15px',
        border: '1px solid #d2d2d7',
        borderRadius: '10px',
        outline: 'none',
        transition: 'all 0.2s',
        fontFamily: 'inherit',
        background: '#fff',
    },
    textarea: {
        width: '100%',
        padding: '14px 16px',
        fontSize: '15px',
        border: '1px solid #d2d2d7',
        borderRadius: '10px',
        outline: 'none',
        transition: 'all 0.2s',
        fontFamily: 'inherit',
        resize: 'vertical',
        background: '#fff',
    },
    inputError: {
        borderColor: '#cc0000',
    },
    errorMessage: {
        color: '#cc0000',
        fontSize: '13px',
        marginTop: '6px',
    },
    charCount: {
        fontSize: '13px',
        color: '#86868b',
        marginTop: '6px',
        textAlign: 'right',
    },
    gridTwo: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '20px',
        marginBottom: '24px',
    },
    searchInput: {
        width: '100%',
        padding: '12px 16px',
        fontSize: '15px',
        border: '1px solid #d2d2d7',
        borderRadius: '10px',
        outline: 'none',
        marginBottom: '16px',
        fontFamily: 'inherit',
    },
    authorList: {
        maxHeight: '300px',
        overflowY: 'auto',
        border: '1px solid #e5e5e7',
        borderRadius: '10px',
        marginBottom: '16px',
    },
    authorItem: {
        padding: '14px 16px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        cursor: 'pointer',
        transition: 'background 0.2s',
        borderBottom: '1px solid #f5f5f7',
    },
    authorItemSelected: {
        background: '#f5f5f7',
    },
    checkbox: {
        width: '20px',
        height: '20px',
        cursor: 'pointer',
        accentColor: '#1d1d1f',
    },
    selectedSection: {
        marginTop: '16px',
    },
    selectedLabel: {
        fontSize: '14px',
        fontWeight: 600,
        color: '#1d1d1f',
        marginBottom: '12px',
    },
    selectedTags: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
    },
    tag: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px 12px',
        background: '#1d1d1f',
        color: '#fff',
        borderRadius: '8px',
        fontSize: '14px',
    },
    tagRemove: {
        background: 'transparent',
        border: 'none',
        color: '#fff',
        cursor: 'pointer',
        fontSize: '16px',
        padding: '0 4px',
        lineHeight: 1,
    },
    genreGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
        gap: '12px',
        marginBottom: '16px',
    },
    genreButton: {
        padding: '12px 16px',
        background: '#fff',
        border: '1px solid #d2d2d7',
        borderRadius: '10px',
        fontSize: '14px',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s',
        color: '#1d1d1f',
    },
    genreButtonActive: {
        background: '#1d1d1f',
        color: '#fff',
        borderColor: '#1d1d1f',
    },
    navigationButtons: {
        display: 'flex',
        gap: '12px',
        paddingTop: '24px',
        borderTop: '1px solid #e5e5e7',
    },
    btnPrimary: {
        padding: '14px 32px',
        background: '#1d1d1f',
        color: '#fff',
        border: 'none',
        borderRadius: '10px',
        fontSize: '17px',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    btnSecondary: {
        padding: '14px 32px',
        background: 'transparent',
        color: '#1d1d1f',
        border: '1px solid #d2d2d7',
        borderRadius: '10px',
        fontSize: '17px',
        fontWeight: 500,
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    btnCancel: {
        padding: '14px 32px',
        background: 'transparent',
        color: '#6e6e73',
        border: '1px solid #e5e5e7',
        borderRadius: '10px',
        fontSize: '17px',
        fontWeight: 400,
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    btnDisabled: {
        opacity: 0.5,
        cursor: 'not-allowed',
    },
    checkbox: {
        accentColor: "#000",
    }
};